# Generated by Django 5.2.11 on 2026-02-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='taluk',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='village',
            new_name='habitation',
        ),
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='complaint_docs/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='mm_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='panchayat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='complaint_mgmt.category')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint_mgmt.subcategory'),
        ),
    ]
